import { useEffect, useMemo } from 'react'
import { useToast } from '@/components/ui/Toast'
import { useMoexCandleJobState } from '@/pages/testing/hooks/useMoexCandleJobState'
import { useTestingCreateRobot } from '@/pages/testing/hooks/useTestingCreateRobot'
import { useTestingRobotForm } from '@/pages/testing/hooks/useTestingRobotForm'
import { useTestingRecommendations } from '@/pages/testing/hooks/useTestingRecommendations'
import { useTestingOptimization } from '@/pages/testing/hooks/useTestingOptimization'
import { useTestingUniverse } from '@/pages/testing/hooks/useTestingUniverse'
import { legacyFormToTestingFormState } from '@/pages/testing/refactored/formAdapter'
import { useTestingResults } from '@/pages/testing/refactored/hooks/useTestingResults'
import { useTestingRunner } from '@/pages/testing/refactored/hooks/useTestingRunner'
import { parseFixedTickersInput } from '@/utils/universeMode'

/**
 * Refactored page controller (T1): 3 hooks — config/runner/results — over legacy form state.
 * Same surface as `useTestingPage` for `TestingPageContent`.
 */
export function useTestingRefactoredPage() {
    const toast = useToast()
    const form = useTestingRobotForm()

    const formState = useMemo(
        () =>
            legacyFormToTestingFormState({
                robotId: form.robotId,
                brokerType: form.brokerType,
                fromDate: form.fromDate,
                toDate: form.toDate,
                capital: form.capital,
                strategy: form.strategy,
                strategyParams: form.strategyParams,
                interval: form.interval,
                stopLossPct: form.stopLossPct,
                takeProfitPct: form.takeProfitPct,
                maxPositionPct: form.maxPositionPct,
                maxPositionRub: form.maxPositionRub,
                maxDailyLoss: form.maxDailyLoss,
                slippagePct: form.slippagePct,
                executionLatencySec: form.executionLatencySec,
                maxDrawdownPct: form.maxDrawdownPct,
                tradingHoursStart: form.tradingHoursStart,
                tradingHoursEnd: form.tradingHoursEnd,
                allowedWeekdays: form.allowedWeekdays,
                brokerCommissionPct: form.brokerCommissionPct,
                ndflPct: form.ndflPct,
                pipelineMode: form.pipelineMode,
                filters: form.filters,
                universeMode: form.universeMode,
                universeRefreshMinutes: form.universeRefreshMinutes,
                fixedTickersText: form.fixedTickersText,
                cryptoUniverseMode: form.cryptoUniverseMode,
                cryptoMinVolume24hUsd: form.cryptoMinVolume24hUsd,
                cryptoMinLastPrice: form.cryptoMinLastPrice,
                cryptoMaxSpreadBps: form.cryptoMaxSpreadBps,
                cryptoMaxFundingRatePct: form.cryptoMaxFundingRatePct,
                cryptoMinFundingRatePct: form.cryptoMinFundingRatePct,
                cryptoMinOpenInterestUsd: form.cryptoMinOpenInterestUsd,
                cryptoMinLsr: form.cryptoMinLsr,
                cryptoMaxLsr: form.cryptoMaxLsr,
                cryptoMinRvol: form.cryptoMinRvol,
                cryptoMinAtrPercent: form.cryptoMinAtrPercent,
                cryptoMaxAtrPercent: form.cryptoMaxAtrPercent,
                cryptoLookbackDays: form.cryptoLookbackDays,
                bybitTestnet: form.bybitTestnet,
                instrumentCategory: form.instrumentCategory,
                leverage: form.leverage,
                makerFeePct: form.makerFeePct,
                takerFeePct: form.takerFeePct,
                fundingMode: form.fundingMode,
                backtestExecution: form.backtestExecution,
                backtestFeeModel: form.backtestFeeModel,
                maintenanceMarginPct: form.maintenanceMarginPct,
                pollValue: form.pollValue,
                pollUnit: form.pollUnit,
            }),
        [
            form.robotId,
            form.brokerType,
            form.fromDate,
            form.toDate,
            form.capital,
            form.strategy,
            form.strategyParams,
            form.interval,
            form.stopLossPct,
            form.takeProfitPct,
            form.maxPositionPct,
            form.maxPositionRub,
            form.maxDailyLoss,
            form.slippagePct,
            form.executionLatencySec,
            form.maxDrawdownPct,
            form.tradingHoursStart,
            form.tradingHoursEnd,
            form.allowedWeekdays,
            form.brokerCommissionPct,
            form.ndflPct,
            form.pipelineMode,
            form.filters,
            form.universeMode,
            form.universeRefreshMinutes,
            form.fixedTickersText,
            form.cryptoUniverseMode,
            form.cryptoMinVolume24hUsd,
            form.cryptoMinLastPrice,
            form.cryptoMaxSpreadBps,
            form.cryptoMaxFundingRatePct,
            form.cryptoMinFundingRatePct,
            form.cryptoMinOpenInterestUsd,
            form.cryptoMinLsr,
            form.cryptoMaxLsr,
            form.cryptoMinRvol,
            form.cryptoMinAtrPercent,
            form.cryptoMaxAtrPercent,
            form.cryptoLookbackDays,
            form.bybitTestnet,
            form.instrumentCategory,
            form.leverage,
            form.makerFeePct,
            form.takerFeePct,
            form.fundingMode,
            form.backtestExecution,
            form.backtestFeeModel,
            form.maintenanceMarginPct,
            form.pollValue,
            form.pollUnit,
        ],
    )

    const results = useTestingResults({ selectedRobotId: form.selectedRobot?.id ?? null })

    const runner = useTestingRunner({
        form: formState,
        robotType: form.selectedRobot?.type ?? null,
        selectedRobot: form.selectedRobot,
        results,
        toast,
        setFromDate: form.setFromDate,
        setToDate: form.setToDate,
        setInvalid: form.setInvalid,
        configDirty: form.configDirty,
        setConfigDirty: form.setConfigDirty,
        setRobots: form.setRobots,
    })

    const backtest = useMemo(
        () => ({
            pipelinePayload: runner.pipelinePayload,
            running: runner.running,
            statusWindow: results.statusWindow,
            result: results.result,
            historyRuns: results.historyRuns,
            historyLoading: results.historyLoading,
            historyError: results.historyError,
            historySearch: results.historySearch,
            setHistorySearch: results.setHistorySearch,
            historyMinReturn: results.historyMinReturn,
            setHistoryMinReturn: results.setHistoryMinReturn,
            historyMarketFilter: results.historyMarketFilter,
            setHistoryMarketFilter: results.setHistoryMarketFilter,
            historyStatusFilter: results.historyStatusFilter,
            setHistoryStatusFilter: results.setHistoryStatusFilter,
            compareLeftId: results.compareLeftId,
            setCompareLeftId: results.setCompareLeftId,
            compareRightId: results.compareRightId,
            setCompareRightId: results.setCompareRightId,
            priceCurve: results.priceCurve,
            chartLegend: results.chartLegend,
            setChartLegend: results.setChartLegend,
            activeDetailsTab: results.activeDetailsTab,
            setActiveDetailsTab: results.setActiveDetailsTab,
            runSignals: results.runSignals,
            runOrders: results.runOrders,
            runPortfolioSnapshots: results.runPortfolioSnapshots,
            error: runner.error,
            persistRobotConfig: runner.persistRobotConfig,
            runBacktest: runner.runBacktest,
            refreshHistoryBacktests: results.refreshHistoryBacktests,
            openHistoryBacktestRun: results.openHistoryBacktestRun,
            openHistoryBacktestRunById: results.openHistoryBacktestRunById,
            filteredHistoryRuns: results.filteredHistoryRuns,
            pollingRunId: runner.pollingRunId,
            cancellingRun: runner.cancellingRun,
            cancelActivePoll: runner.cancelActivePoll,
            runProgress: runner.runProgress,
            validate: runner.validate,
            buildPayload: runner.buildPayload,
        }),
        [runner, results],
    )

    const tradingFormSnapshot = useMemo(
        () => ({
            strategy: form.strategy,
            strategyParams: form.strategyParams,
            interval: form.interval,
            capital: form.capital,
            brokerType: form.brokerType,
            stopLossPct: form.stopLossPct,
            takeProfitPct: form.takeProfitPct,
            maxPositionPct: form.maxPositionPct,
            maxPositionRub: form.maxPositionRub,
            maxDailyLoss: form.maxDailyLoss,
            slippagePct: form.slippagePct,
            executionLatencySec: form.executionLatencySec,
            maxDrawdownPct: form.maxDrawdownPct,
            tradingHoursStart: form.tradingHoursStart,
            tradingHoursEnd: form.tradingHoursEnd,
            allowedWeekdays: form.allowedWeekdays,
            brokerCommissionPct: form.brokerCommissionPct,
            ndflPct: form.ndflPct,
            pipelineMode: form.pipelineMode,
            filters: form.filters,
            universeRefreshMinutes: form.universeRefreshMinutes,
            universeMode: form.universeMode,
            fixedTickers: parseFixedTickersInput(form.fixedTickersText),
            cryptoUniverseMode: form.cryptoUniverseMode,
            cryptoMinVolume24hUsd: form.cryptoMinVolume24hUsd,
            cryptoMinLastPrice: form.cryptoMinLastPrice,
            cryptoMaxSpreadBps: form.cryptoMaxSpreadBps,
            cryptoMaxFundingRatePct: form.cryptoMaxFundingRatePct,
            cryptoMinFundingRatePct: form.cryptoMinFundingRatePct,
            cryptoMinOpenInterestUsd: form.cryptoMinOpenInterestUsd,
            cryptoMinLsr: form.cryptoMinLsr,
            cryptoMaxLsr: form.cryptoMaxLsr,
            cryptoMinRvol: form.cryptoMinRvol,
            cryptoMinAtrPercent: form.cryptoMinAtrPercent,
            cryptoMaxAtrPercent: form.cryptoMaxAtrPercent,
            cryptoLookbackDays: form.cryptoLookbackDays,
            bybitTestnet: form.bybitTestnet,
            instrumentCategory: form.instrumentCategory,
            leverage: form.leverage,
            makerFeePct: form.makerFeePct,
            takerFeePct: form.takerFeePct,
            fundingMode: form.fundingMode,
            backtestExecution: form.backtestExecution,
            backtestFeeModel: form.backtestFeeModel,
            maintenanceMarginPct: form.maintenanceMarginPct,
            pollValue: form.pollValue,
            pollUnit: form.pollUnit,
            mergeStrategyParamsFrom: undefined as Record<string, unknown> | undefined,
        }),
        [
            form.strategy,
            form.strategyParams,
            form.interval,
            form.capital,
            form.brokerType,
            form.stopLossPct,
            form.takeProfitPct,
            form.maxPositionPct,
            form.maxPositionRub,
            form.maxDailyLoss,
            form.slippagePct,
            form.executionLatencySec,
            form.maxDrawdownPct,
            form.tradingHoursStart,
            form.tradingHoursEnd,
            form.allowedWeekdays,
            form.brokerCommissionPct,
            form.ndflPct,
            form.pipelineMode,
            form.filters,
            form.universeRefreshMinutes,
            form.universeMode,
            form.fixedTickersText,
            form.cryptoUniverseMode,
            form.cryptoMinVolume24hUsd,
            form.cryptoMinLastPrice,
            form.cryptoMaxSpreadBps,
            form.cryptoMaxFundingRatePct,
            form.cryptoMinFundingRatePct,
            form.cryptoMinOpenInterestUsd,
            form.cryptoMinLsr,
            form.cryptoMaxLsr,
            form.cryptoMinRvol,
            form.cryptoMinAtrPercent,
            form.cryptoMaxAtrPercent,
            form.cryptoLookbackDays,
            form.bybitTestnet,
            form.instrumentCategory,
            form.leverage,
            form.makerFeePct,
            form.takerFeePct,
            form.fundingMode,
            form.backtestExecution,
            form.backtestFeeModel,
            form.maintenanceMarginPct,
            form.pollValue,
            form.pollUnit,
        ],
    )

    const universe = useTestingUniverse({
        selectedRobot: form.selectedRobot,
        toast,
        setRobots: form.setRobots,
    })

    const createRobot = useTestingCreateRobot(
        tradingFormSnapshot,
        form.setRobots,
        form.setRobotId,
        toast,
    )

    const recommendations = useTestingRecommendations(form.robotId)
    const optimization = useTestingOptimization(form.robotId)

    useEffect(() => {
        if (backtest.result) {
            void recommendations.refresh()
            void optimization.refreshRank()
        }
    }, [backtest.result, recommendations.refresh, optimization.refreshRank])

    const moexJob = useMoexCandleJobState({
        fromDate: form.fromDate,
        toDate: form.toDate,
        signalInterval: form.interval,
        selectedRobot: form.selectedRobot,
        pipelinePayload: backtest.pipelinePayload,
        pipelineMode: form.pipelineMode,
        toast,
    })

    return { form, backtest, moexJob, createRobot, recommendations, optimization, universe }
}

export type TestingRefactoredPageController = ReturnType<typeof useTestingRefactoredPage>
